lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
# This is a demo rake file

require 'rototiller'

Rototiller::Task::RototillerTask.define_task :demo do |t|
  t.add_env('FOO', 'I am describing FOO', 'FOO default')
  t.add_env('HOME', 'I am describing HOME')

  t.add_flag('--flag', 'I am describing --flag', 'flag/default')

  t.command = 'echo my_sweet_command'
end
